name: CI
on:
  - push
  - pull_request

jobs:
  cabal:
    name: Build & Test - ${{ matrix.os }} - ${{ matrix.ghc }}
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.0.2"
          - "9.2.7"
          - "9.4.4"
          - "9.6.1"
        os:
        - "macos-latest"
        - "ubuntu-latest"
        - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.5.0

      - uses: haskell/actions/setup@v2.3.7
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Build
        run: cabal build

      - name: Test
        run: cabal run test

