name: CI
on:
  push:
    branches:
      - main

  pull_request:

jobs:
  cabal:
    name: Build & Test - ${{ matrix.os }} - ${{ matrix.ghc }}
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "9.0.2"
          - "9.2.8"
          - "9.4.8"
          - "9.6.4"
          - "9.8.2"
        os:
        - "macos-latest"
        - "ubuntu-latest"
        - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.5.0

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}

      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project', 'cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-
          path: dist-newstyle/build

      - name: Build
        run: cabal build

      - name: Test
        run: cabal run test

